/*****************************************************************************************
 * MacModelsData.swift
 *
 * Embedded Mac model identifier database (generated from macs.json)
 *
 * Source   :  https://github.com/TelemetryDeck/AppleModelNames/blob/main/dataset/macs.json
 *
 * Author   :  Gary Ash <gary.ash@icloud.com>
 * Created  :   9-Jun-2026  3:52pm
 * Modified :   9-Jun-2026  3:52pm
 *
 * Copyright © 2026 By Gary Ash All rights reserved.
 ****************************************************************************************/

struct MacModel {
    let readableName: String
    let deviceType: String?
    let processorType: String?
    let processorFamily: String?
    let systemFirstRelease: String?
    let systemLastRelease: String?
}

let macModels: [String: MacModel] = [
    "Mac13,1": MacModel(readableName: "Mac Studio (2022)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M1 Max or M1 Ultra", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac13,2": MacModel(readableName: "Mac Studio (2022)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M1 Max or M1 Ultra", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac14,10": MacModel(readableName: "MacBook Pro (M2 Pro, 16-inch, 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2 Pro", systemFirstRelease: nil, systemLastRelease: nil),
    "Mac14,12": MacModel(readableName: "Mac mini (2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M2 Pro", systemFirstRelease: "13.0", systemLastRelease: nil),
    "Mac14,13": MacModel(readableName: "Mac Studio (2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M2 Max or M2 Ultra", systemFirstRelease: "13.4", systemLastRelease: nil),
    "Mac14,14": MacModel(readableName: "Mac Studio (2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M2 Max or M2 Ultra", systemFirstRelease: "13.4", systemLastRelease: nil),
    "Mac14,15": MacModel(readableName: "MacBook Air (15-inch, M2, 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2", systemFirstRelease: nil, systemLastRelease: nil),
    "Mac14,2": MacModel(readableName: "MacBook Air (M2, 2022)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2", systemFirstRelease: "12.4", systemLastRelease: nil),
    "Mac14,3": MacModel(readableName: "Mac mini (2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M2", systemFirstRelease: "13.0", systemLastRelease: nil),
    "Mac14,5": MacModel(readableName: "MacBook Pro (14-inch, 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2 Max or M2 Pro", systemFirstRelease: "13.0", systemLastRelease: nil),
    "Mac14,6": MacModel(readableName: "MacBook Pro (16-inch, 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2 Max or M2 Pro", systemFirstRelease: "13.0", systemLastRelease: nil),
    "Mac14,7": MacModel(readableName: "MacBook Pro (13-inch, M2, 2022)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2", systemFirstRelease: "12.4", systemLastRelease: nil),
    "Mac14,8": MacModel(readableName: "Mac Pro (2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M2 Ultra", systemFirstRelease: "13.4 (22F2063)", systemLastRelease: nil),
    "Mac14,9": MacModel(readableName: "MacBook Pro (M2 Pro, 14-inch, 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M2 Pro", systemFirstRelease: nil, systemLastRelease: nil),
    "Mac15,10": MacModel(readableName: "MacBook Pro (14-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3 Max", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac15,11": MacModel(readableName: "MacBook Pro (16-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3 Max", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac15,12": MacModel(readableName: "MacBook Air (13-inch, M3, 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3", systemFirstRelease: "14.4", systemLastRelease: nil),
    "Mac15,13": MacModel(readableName: "MacBook Air (15-inch, M3, 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3", systemFirstRelease: "14.4", systemLastRelease: nil),
    "Mac15,14": MacModel(readableName: "Mac Studio (M3 Ultra, 2025)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M3 Ultra", systemFirstRelease: "15.3.1", systemLastRelease: nil),
    "Mac15,3": MacModel(readableName: "MacBook Pro (14-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3", systemFirstRelease: "13.5", systemLastRelease: nil),
    "Mac15,4": MacModel(readableName: "iMac (24-inch, 2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M3", systemFirstRelease: "13.5 (22G2074)", systemLastRelease: nil),
    "Mac15,5": MacModel(readableName: "iMac (24-inch, 2023)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M3", systemFirstRelease: "13.5 (22G2074)", systemLastRelease: nil),
    "Mac15,6": MacModel(readableName: "MacBook Pro (14-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3 Pro", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac15,7": MacModel(readableName: "MacBook Pro (16-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3 Pro or M3 Max", systemFirstRelease: "14.1", systemLastRelease: nil),
    "Mac15,8": MacModel(readableName: "MacBook Pro (14-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3 Max", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac15,9": MacModel(readableName: "MacBook Pro (16-inch, Nov 2023)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M3 Max", systemFirstRelease: "12.2", systemLastRelease: nil),
    "Mac16,1": MacModel(readableName: "MacBook Pro (14-inch, Nov 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,10": MacModel(readableName: "Mac mini (2024)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M4", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,11": MacModel(readableName: "Mac mini (2024)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M4 Pro", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,12": MacModel(readableName: "MacBook Air (13-inch, M4, 2025)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,13": MacModel(readableName: "MacBook Air (15-inch, M4, 2025)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,2": MacModel(readableName: "iMac (24-inch, 2024)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M4", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,3": MacModel(readableName: "iMac (24-inch, 2024)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M4", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,5": MacModel(readableName: "MacBook Pro (16-inch, Nov 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4 Max", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,6": MacModel(readableName: "MacBook Pro (14-inch, Nov 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4 Pro", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,7": MacModel(readableName: "MacBook Pro (16-inch, Nov 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4 Pro", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,8": MacModel(readableName: "MacBook Pro (14-inch, Nov 2024)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M4 Max", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac16,9": MacModel(readableName: "Mac Studio (2025)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M4 Max", systemFirstRelease: "15.0", systemLastRelease: nil),
    "Mac17,2": MacModel(readableName: "MacBook Pro (14-inch, M5, 2025)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M5", systemFirstRelease: "15.1", systemLastRelease: nil),
    "Mac17,5": MacModel(readableName: "Apple MacBook Neo A18 Pro 6 CPU/5 GPU 13 inch", deviceType: "Laptop", processorType: "A18 Pro", processorFamily: nil, systemFirstRelease: "26.3.0", systemLastRelease: nil),
    "MacBook10,1": MacModel(readableName: "MacBook (Retina, 12-inch, 2017)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "MacBook5,1": MacModel(readableName: "MacBook (Late 2008)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "MacBook7,1": MacModel(readableName: "MacBook (Mid 2010)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Core 2 Duo", systemFirstRelease: nil, systemLastRelease: nil),
    "MacBook8,1": MacModel(readableName: "MacBook (12-inch, Early 2015)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Core M", systemFirstRelease: nil, systemLastRelease: nil),
    "MacBook9,1": MacModel(readableName: "MacBook (12-inch, Early 2016)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookAir1,1": MacModel(readableName: "MacBook Air (Early 2008)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Core 2 Duo", systemFirstRelease: "10.5.1", systemLastRelease: "10.7.5"),
    "MacBookAir10,1": MacModel(readableName: "MacBook Air (M1, 2020)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M1", systemFirstRelease: "11.0", systemLastRelease: nil),
    "MacBookAir2,1": MacModel(readableName: "MacBook Air (Late 2008)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Core 2 Duo", systemFirstRelease: "10.5.5", systemLastRelease: "10.11.6"),
    "MacBookAir3,1": MacModel(readableName: "MacBook Air (Late 2010)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Core 2 Duo", systemFirstRelease: "10.6.4", systemLastRelease: "10.13.6"),
    "MacBookAir4,1": MacModel(readableName: "MacBook Air (Mid 2011)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.7.3", systemLastRelease: "10.13.6"),
    "MacBookAir4,2": MacModel(readableName: "MacBook Air (Mid 2011)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookAir5,1": MacModel(readableName: "MacBook Air (Mid 2012)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.7.4", systemLastRelease: "10.15.7"),
    "MacBookAir5,2": MacModel(readableName: "MacBook Air (Mid 2012)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookAir6,1": MacModel(readableName: "MacBook Air (Mid 2013)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.8.4", systemLastRelease: "11.7.10"),
    "MacBookAir6,2": MacModel(readableName: "MacBook Air (Mid 2013)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookAir7,1": MacModel(readableName: "MacBook Air (Early 2014)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.9.2", systemLastRelease: "11.7.10"),
    "MacBookAir7,2": MacModel(readableName: "MacBook Air (2017)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.12.5", systemLastRelease: nil),
    "MacBookAir8,1": MacModel(readableName: "MacBook Air (2018)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.14.5", systemLastRelease: nil),
    "MacBookAir8,2": MacModel(readableName: "MacBook Air (2019)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.14.5", systemLastRelease: nil),
    "MacBookAir9,1": MacModel(readableName: "MacBook Air (2020)", deviceType: "Laptop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.15.3", systemLastRelease: nil),
    "MacBookPro1,1": MacModel(readableName: "MacBook Pro (Early 2006)", deviceType: "Laptop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4.5", systemLastRelease: "10.6.8"),
    "MacBookPro1,2": MacModel(readableName: "MacBook Pro (Early 2006)", deviceType: "Laptop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4.6", systemLastRelease: "10.6.8"),
    "MacBookPro10,1": MacModel(readableName: "MacBook Pro (Retina, Mid 2012)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.7.4", systemLastRelease: "10.15.7"),
    "MacBookPro10,2": MacModel(readableName: "MacBook Pro (Retina, Mid 2012)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.7.4", systemLastRelease: "10.15.7"),
    "MacBookPro11,1": MacModel(readableName: "MacBook Pro (Late 2013)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.9", systemLastRelease: "11.6"),
    "MacBookPro11,2": MacModel(readableName: "MacBook Pro (Late 2013)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.9", systemLastRelease: "11.6"),
    "MacBookPro11,3": MacModel(readableName: "MacBook Pro (Late 2013)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.9", systemLastRelease: "11.6"),
    "MacBookPro11,4": MacModel(readableName: "MacBook Pro (Mid 2015)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.10.2", systemLastRelease: "11.6"),
    "MacBookPro11,5": MacModel(readableName: "MacBook Pro (Mid 2015)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.10.2", systemLastRelease: "11.6"),
    "MacBookPro12,1": MacModel(readableName: "MacBook Pro (13-inch, Early 2015)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5", systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookPro13,1": MacModel(readableName: "MacBook Pro (Late 2016)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.12.1", systemLastRelease: "11.6"),
    "MacBookPro13,2": MacModel(readableName: "MacBook Pro (Late 2016)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.12.1", systemLastRelease: "11.6"),
    "MacBookPro13,3": MacModel(readableName: "MacBook Pro (Late 2016)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.12.1", systemLastRelease: "11.6"),
    "MacBookPro14,1": MacModel(readableName: "MacBook Pro (Late 2016)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.12.1", systemLastRelease: "11.6"),
    "MacBookPro14,2": MacModel(readableName: "MacBook Pro (Late 2016)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.12.1", systemLastRelease: "11.6"),
    "MacBookPro14,3": MacModel(readableName: "MacBook Pro (Late 2017)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.13.2", systemLastRelease: "11.6"),
    "MacBookPro15,1": MacModel(readableName: "MacBook Pro (Mid 2018)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.13.6", systemLastRelease: "11.6"),
    "MacBookPro15,2": MacModel(readableName: "MacBook Pro (Mid 2018)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.13.6", systemLastRelease: "11.6"),
    "MacBookPro15,3": MacModel(readableName: "MacBook Pro (Mid 2018)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i9", systemFirstRelease: "10.13.6", systemLastRelease: "11.6"),
    "MacBookPro15,4": MacModel(readableName: "MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.14.5", systemLastRelease: "11.6"),
    "MacBookPro15,5": MacModel(readableName: "MacBook Pro (15-inch, 2019)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.14.5", systemLastRelease: "11.6"),
    "MacBookPro16,1": MacModel(readableName: "MacBook Pro (16-inch, 2019)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7 or i9", systemFirstRelease: "10.15.1", systemLastRelease: "11.6"),
    "MacBookPro16,2": MacModel(readableName: "MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.15.1", systemLastRelease: "11.6"),
    "MacBookPro16,3": MacModel(readableName: "MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.15.1", systemLastRelease: "11.6"),
    "MacBookPro16,4": MacModel(readableName: "MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.15.1", systemLastRelease: "11.6"),
    "MacBookPro16,5": MacModel(readableName: "MacBook Pro (16-inch, 2019)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i9", systemFirstRelease: "10.15.1", systemLastRelease: "11.6"),
    "MacBookPro17,1": MacModel(readableName: "MacBook Pro (13-inch, M1, 2020)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M1", systemFirstRelease: "11.0", systemLastRelease: nil),
    "MacBookPro18,1": MacModel(readableName: "MacBook Pro (16-inch, 2021)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M1 Pro or M1 Max", systemFirstRelease: "12.0", systemLastRelease: nil),
    "MacBookPro18,2": MacModel(readableName: "MacBook Pro (16-inch, 2021)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M1 Max", systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookPro18,3": MacModel(readableName: "MacBook Pro (14-inch, 2021)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M1 Pro or M1 Max", systemFirstRelease: "12.0", systemLastRelease: nil),
    "MacBookPro18,4": MacModel(readableName: "MacBook Pro (14-inch, 2021)", deviceType: "Laptop", processorType: "Apple Silicon", processorFamily: "M1 Max", systemFirstRelease: nil, systemLastRelease: nil),
    "MacBookPro2,1": MacModel(readableName: "MacBook Pro (Late 2006)", deviceType: "Laptop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4.8", systemLastRelease: "10.7.5"),
    "MacBookPro3,1": MacModel(readableName: "MacBook Pro (Mid 2007)", deviceType: "Laptop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4.10", systemLastRelease: "10.11.6"),
    "MacBookPro4,1": MacModel(readableName: "MacBook Pro (Early 2008)", deviceType: "Laptop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.5.2", systemLastRelease: "10.11.6"),
    "MacBookPro5,1": MacModel(readableName: "MacBook Pro (Late 2008)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.5", systemLastRelease: "10.13.6"),
    "MacBookPro5,2": MacModel(readableName: "MacBook Pro (Mid 2009)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.7", systemLastRelease: "10.13.6"),
    "MacBookPro5,3": MacModel(readableName: "MacBook Pro (Mid 2009)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.7", systemLastRelease: "10.13.6"),
    "MacBookPro5,4": MacModel(readableName: "MacBook Pro (Mid 2009)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.7", systemLastRelease: "10.13.6"),
    "MacBookPro5,5": MacModel(readableName: "MacBook Pro (Mid 2009)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.7", systemLastRelease: "10.13.6"),
    "MacBookPro5,6": MacModel(readableName: "MacBook Pro (Mid 2009)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.7", systemLastRelease: "10.13.6"),
    "MacBookPro5,7": MacModel(readableName: "MacBook Pro (Mid 2009)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.5.7", systemLastRelease: "10.13.6"),
    "MacBookPro6,1": MacModel(readableName: "MacBook Pro (Mid 2010)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.6.3", systemLastRelease: "10.13.6"),
    "MacBookPro6,2": MacModel(readableName: "MacBook Pro (Mid 2010)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.6.3", systemLastRelease: "10.13.6"),
    "MacBookPro7,1": MacModel(readableName: "MacBook Pro (Mid 2010)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core 2 Duo", systemFirstRelease: "10.6.4", systemLastRelease: "10.13.6"),
    "MacBookPro8,1": MacModel(readableName: "MacBook Pro (Early 2011)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.6.6", systemLastRelease: "10.15.7"),
    "MacBookPro8,2": MacModel(readableName: "MacBook Pro (Early 2011)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.6.6", systemLastRelease: "10.15.7"),
    "MacBookPro8,3": MacModel(readableName: "MacBook Pro (Early 2011)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.6.6", systemLastRelease: "10.15.7"),
    "MacBookPro9,1": MacModel(readableName: "MacBook Pro (Mid 2012)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i7", systemFirstRelease: "10.7.4", systemLastRelease: "10.15.7"),
    "MacBookPro9,2": MacModel(readableName: "MacBook Pro (Mid 2012)", deviceType: "Laptop", processorType: "Intel", processorFamily: "Intel Core i5 or i7", systemFirstRelease: "10.7.4", systemLastRelease: "10.15.7"),
    "MacPro1,1": MacModel(readableName: "Mac Pro (Mid 2006)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.7", systemLastRelease: "10.7.5"),
    "MacPro2,1": MacModel(readableName: "Mac Pro (Mid 2006)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.7", systemLastRelease: "10.7.5"),
    "MacPro3,1": MacModel(readableName: "Mac Pro (Early 2008)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.5.1", systemLastRelease: "10.11.6"),
    "MacPro4,1": MacModel(readableName: "Mac Pro (Early 2009)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.5.6", systemLastRelease: "10.11.6"),
    "MacPro5,1": MacModel(readableName: "Mac Pro (Mid 2010)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.4", systemLastRelease: "10.14.6"),
    "MacPro6,1": MacModel(readableName: "Mac Pro (Late 2013)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.9.1", systemLastRelease: nil),
    "MacPro7,1": MacModel(readableName: "Mac Pro (2019)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.15.1", systemLastRelease: nil),
    "Macmini1,1": MacModel(readableName: "Mac mini (Early 2006)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4", systemLastRelease: "10.6.8"),
    "Macmini2,1": MacModel(readableName: "Mac mini (Mid 2007)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4", systemLastRelease: "10.6.8"),
    "Macmini3,1": MacModel(readableName: "Mac mini (Early 2009)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.5", systemLastRelease: "10.11.6"),
    "Macmini4,1": MacModel(readableName: "Mac mini (Mid 2010)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6", systemLastRelease: "10.13.6"),
    "Macmini5,1": MacModel(readableName: "Mac mini (Mid 2011)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.7", systemLastRelease: "10.13.6"),
    "Macmini6,1": MacModel(readableName: "Mac mini (Late 2012)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.8", systemLastRelease: "10.15.7"),
    "Macmini6,2": MacModel(readableName: "Mac mini (Late 2012)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "Macmini7,1": MacModel(readableName: "Mac mini (Late 2014)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.10", systemLastRelease: nil),
    "Macmini8,1": MacModel(readableName: "Mac mini (2018)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.14", systemLastRelease: nil),
    "Macmini9,1": MacModel(readableName: "Mac mini (M1, 2020)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M1", systemFirstRelease: "11.0", systemLastRelease: nil),
    "PowerMac10,1": MacModel(readableName: "Mac mini (Early 2005)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.3", systemLastRelease: "10.5.8"),
    "PowerMac10,2": MacModel(readableName: "Mac mini (Late 2005)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4", systemLastRelease: "10.6.8"),
    "PowerMac12,1": MacModel(readableName: "iMac G5 (iSight 20-inch)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4.2", systemLastRelease: "10.5.8"),
    "PowerMac2,1": MacModel(readableName: "iMac G3 (Slot Loading)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "8.6", systemLastRelease: "10.4.11"),
    "PowerMac2,2": MacModel(readableName: "iMac G3 (Summer 2000 or Early 2001)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "9.0.4", systemLastRelease: "10.4.11"),
    "PowerMac4,2": MacModel(readableName: "iMac G4 (2002)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "9.2.2", systemLastRelease: "10.4.11"),
    "PowerMac6,1": MacModel(readableName: "iMac G4 (2003)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.2.3", systemLastRelease: "10.5.8"),
    "PowerMac6,2": MacModel(readableName: "iMac G4 (USB 2.0)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.2.3", systemLastRelease: "10.5.8"),
    "PowerMac8,1": MacModel(readableName: "iMac G5", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.3.5", systemLastRelease: "10.5.8"),
    "PowerMac8,2": MacModel(readableName: "iMac G5 (Ambient Light Sensor)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "10.4", systemLastRelease: "10.5.8"),
    "VirtualMac2,1": MacModel(readableName: "Apple Virtual Machine 1", deviceType: "Virtual Machine", processorType: nil, processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "iMac,1": MacModel(readableName: "iMac G3 (1998 and 1999)", deviceType: "Desktop", processorType: "PowerPC", processorFamily: nil, systemFirstRelease: "8.1", systemLastRelease: "10.3.9"),
    "iMac10,1": MacModel(readableName: "iMac (21.5-inch, Late 2009)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.1", systemLastRelease: "10.13.6"),
    "iMac11,1": MacModel(readableName: "iMac (21.5-inch, Late 2009)", deviceType: nil, processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.1", systemLastRelease: "10.13.6"),
    "iMac11,2": MacModel(readableName: "iMac (27-inch, Late 2009)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.3", systemLastRelease: "10.13.6"),
    "iMac11,3": MacModel(readableName: "iMac (21.5-inch, Mid 2010)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.3", systemLastRelease: "10.13.6"),
    "iMac12,1": MacModel(readableName: "iMac (21.5-inch, 2011)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.6", systemLastRelease: "10.13.6"),
    "iMac12,2": MacModel(readableName: "iMac (27-inch, Mid 2011 or Mid 2010)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.6.6", systemLastRelease: "10.13.6"),
    "iMac13,1": MacModel(readableName: "iMac (21.5-inch, Late 2012 or Early 2013)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.8.2", systemLastRelease: "10.15.7"),
    "iMac13,2": MacModel(readableName: "iMac (27-inch, Late 2012)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.8.2", systemLastRelease: "10.15.7"),
    "iMac14,1": MacModel(readableName: "iMac (21.5-inch, Late 2013)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.8.4", systemLastRelease: "10.15.7"),
    "iMac14,2": MacModel(readableName: "iMac (27-inch, Late 2013)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.8.4", systemLastRelease: "10.15.7"),
    "iMac14,3": MacModel(readableName: "iMac (Late 2013)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: nil, systemLastRelease: nil),
    "iMac14,4": MacModel(readableName: "iMac (21.5-inch, Mid 2014)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.9.3", systemLastRelease: "11.7.10"),
    "iMac15,1": MacModel(readableName: "iMac (Retina 5K, 27-inch, Late 2014 or Mid 2015)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.10", systemLastRelease: "11.7.10"),
    "iMac16,1": MacModel(readableName: "iMac (21.5-inch, Late 2015)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.11", systemLastRelease: "11.7.10"),
    "iMac16,2": MacModel(readableName: "iMac (Retina 4K, 21.5-inch, Late 2015)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.11", systemLastRelease: "11.7.10"),
    "iMac17,1": MacModel(readableName: "iMac (Retina 5K, 27-inch, Late 2015)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.11", systemLastRelease: "11.7.10"),
    "iMac18,1": MacModel(readableName: "iMac (21.5-inch, 2017)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.12.4", systemLastRelease: "11.7.10"),
    "iMac18,2": MacModel(readableName: "iMac (Retina 4K, 21.5-inch, 2017)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.12.4", systemLastRelease: "11.7.10"),
    "iMac18,3": MacModel(readableName: "iMac (Retina 5K, 27-inch, 2017)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.12.4", systemLastRelease: "11.7.10"),
    "iMac19,1": MacModel(readableName: "iMac (Retina 5K, 27-inch, 2019)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.14.4", systemLastRelease: nil),
    "iMac19,2": MacModel(readableName: "iMac (Retina 4K, 21.5-inch, 2019)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.14.4", systemLastRelease: nil),
    "iMac20,1": MacModel(readableName: "iMac (Retina 5K, 27-inch, 2020)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.15.6", systemLastRelease: nil),
    "iMac20,2": MacModel(readableName: "iMac (Retina 5K, 27-inch, 2020)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.15.6", systemLastRelease: nil),
    "iMac21,1": MacModel(readableName: "iMac (24-inch, M1, 2021)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M1", systemFirstRelease: "11.3 (20E232)", systemLastRelease: nil),
    "iMac21,2": MacModel(readableName: "iMac (24-inch, M1, 2021)", deviceType: "Desktop", processorType: "Apple Silicon", processorFamily: "M1", systemFirstRelease: "11.3 (20E232)", systemLastRelease: nil),
    "iMac4,1": MacModel(readableName: "iMac (17-inch, Early 2006)", deviceType: nil, processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.4", systemLastRelease: "10.6.8"),
    "iMac4,2": MacModel(readableName: "iMac (17-inch, Mid 2006)", deviceType: nil, processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.7", systemLastRelease: "10.6.8"),
    "iMac5,1": MacModel(readableName: "iMac (20-inch, Late 2006)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.7", systemLastRelease: "10.7.5"),
    "iMac5,2": MacModel(readableName: "iMac (17-inch, Late 2006)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.7", systemLastRelease: "10.7.5"),
    "iMac6,1": MacModel(readableName: "iMac (24-inch, Late 2006)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.7", systemLastRelease: "10.7.5"),
    "iMac7,1": MacModel(readableName: "iMac (20-inch or 24-inch, Mid 2007)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.4.10", systemLastRelease: "10.11.6"),
    "iMac8,1": MacModel(readableName: "iMac (20-inch or 24-inch, Early 2008)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.5.2", systemLastRelease: "10.11.6"),
    "iMac9,1": MacModel(readableName: "iMac (20-inch or 24-inch, 2009)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.5.6", systemLastRelease: "10.11.6"),
    "iMacPro1,1": MacModel(readableName: "iMac Pro (2017)", deviceType: "Desktop", processorType: "Intel", processorFamily: nil, systemFirstRelease: "10.13.2", systemLastRelease: nil),
]
